name: Deploy to S3 and Invalidate CloudFront Cache

on:
  push:
    branches:
      - main # main 브랜치에 푸시하면 자동 배포

jobs:
  deploy:
    runs-on: ubuntu-latest # GitHub Actions 실행 환경

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-northeast-1

      - name: Deploy to S3
        run: aws s3 sync public/ s3://www.javierju.com --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E1GPXIPESV5ZA2 --paths "/*"
