name: Deploy to S3 and Invalidate CloudFront Cache

on:
  push:
    branches:
      - main # main 브랜치에 푸시하면 자동 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 모든 커밋을 가져옴 (HEAD~1을 사용할 수 있게 함)

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Lint Check
        run: npm run lint

      - name: Auto-fix Lint Issues
        run: npm run lint:fix

      - name: Re-run Lint Check After Fix
        run: npm run lint

      - name: Format Code
        run: npm run format && git diff --exit-code || (echo "Code format incorrect. Please run 'npm run format' locally before pushing." && exit 1)

      - name: Check if SASS Files Changed
        id: sass_check
        run: |
          if git diff --name-only --diff-filter=AMR HEAD^ HEAD | grep -E 'sass/.*\.scss$'; then
            echo "sass_changed=true" >> $GITHUB_ENV
          else
            echo "sass_changed=false" >> $GITHUB_ENV
          fi

      - name: Build Project (Generate style.css)
        if: env.sass_changed == 'true'
        run: npm run build

      - name: Commit and Push Changes (style.css)
        if: env.sass_changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/css/style.css public/css/style.css.map || echo "style.css or style.css.map not found, skipping commit."
          git diff --staged --quiet || (git commit -m "Auto-generate style.css and style.css.map from updated SASS files" && git push origin main)

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-northeast-1

      - name: Deploy to S3
        run: aws s3 sync public/ s3://www.javierju.com --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E1GPXIPESV5ZA2 --paths "/*"
